# Generated by Django 5.1.2 on 2024-10-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_users', models.IntegerField()),
                ('total_transactions', models.IntegerField()),
                ('traffic_issues', models.IntegerField()),
            ],
        ),
    ]
