# Generated by Django 5.1.2 on 2024-10-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
