# Generated by Django 5.1.2 on 2024-10-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0002_alter_analyticsdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsdata',
            name='date',
        ),
    ]
