# Generated by Django 5.1.2 on 2024-10-21 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_transport', '0003_publictransport_current_latitude_and_more'),
        ('reviews', '0003_review_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public_transport.publictransport'),
        ),
    ]
