# Generated by Django 5.1.2 on 2024-10-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=200)),
                ('bus_number', models.CharField(max_length=30)),
                ('available_seats', models.IntegerField()),
                ('next_arrival_time', models.TimeField()),
            ],
        ),
    ]
