# Generated by Django 5.1.2 on 2024-10-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publictransport',
            name='next_arrival_time',
        ),
    ]
