# Generated by Django 5.1.2 on 2024-10-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_transport', '0002_remove_publictransport_next_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictransport',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='publictransport',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
    ]
