# Generated by Django 5.1.2 on 2024-10-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficupdate',
            name='status',
            field=models.CharField(choices=[('TRAFFIC', 'TRAFFIC'), ('NO TRAFFIC', 'NO TRAFFIC')], max_length=50),
        ),
    ]
