# Generated by Django 5.1.2 on 2024-10-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0002_alter_trafficupdate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficupdate',
            name='status',
            field=models.CharField(choices=[('Heavy', 'Heavy'), ('Normal', 'Normal'), ('Light', 'Light')], max_length=50),
        ),
    ]
