# Generated by Django 5.1.2 on 2024-10-19 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyservice',
            name='times_dates',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
