# Generated by Django 5.1.2 on 2024-10-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_safety', '0002_emergencyservice_times_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyservice',
            name='times_dates',
        ),
    ]
